package hello.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "DevDemoGreeting")
public class Greeting {

	private String lang;
	private String hello;

	public Greeting() {
	}

	public Greeting(String lang, String hello) {
		this.lang = lang;
		this.hello = hello;
	}

	@DynamoDBHashKey
	public String getLang() {
		return lang;
	}

	@DynamoDBAttribute
	public String getHello() {
		return hello;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public void setHello(String hello) {
		this.hello = hello;
	}

}